"""PR delivery for a verified Deploy Pack — GitHub REST (Git Data API).

Accepts whatever token the caller passes in. app/main.py resolves that
token: a GitHub App installation token when GITHUB_APP_ID +
GITHUB_APP_PRIVATE_KEY are configured (see app/deploypack/github_app.py
— works for any repo the App is installed on), falling back to the
single-operator GITHUB_PR_TOKEN below otherwise. This module itself
stays auth-agnostic — it doesn't know or care which kind of token it got.

Never pushes to the base branch directly: creates a new branch, commits
there, opens a PR. Merge stays with the repo owner (HITL), same
principle as everywhere else in this codebase. A caller MUST only call
this after sandbox verification succeeds — see app/main.py, which
refuses to deliver an unverified Pack.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

import httpx

GITHUB_API = "https://api.github.com"
_HEADERS_BASE = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


class DeliveryError(Exception):
    """A GitHub API call failed; message includes which step and why."""


@dataclass
class PullRequestResult:
    html_url: str
    branch: str


def token_from_env() -> str | None:
    return os.environ.get("GITHUB_PR_TOKEN") or None


def render_pr_body(pack: str, files: dict[str, str], detail: str) -> str:
    """Human-readable PR description — non-technical users need to
    understand what changed and why before they merge anything."""
    file_list = "\n".join(f"- `{path}`" for path in sorted(files))
    return (
        f"## Drydock {pack.title()} Pack\n\n"
        f"Verified in a sandbox before this PR was opened: `docker build` "
        f"+ `docker run` + a real HTTP request confirmed the app boots.\n\n"
        f"**Verification result:** {detail}\n\n"
        f"### Files added or changed\n{file_list}\n\n"
        "### How to check it yourself\n"
        "```bash\ndocker compose up --build\n```\n"
        "Merge is entirely up to you — nothing here touches your base "
        "branch until you press merge.\n"
    )


def open_pull_request(
    owner: str,
    repo: str,
    files: dict[str, str],
    *,
    base_branch: str = "main",
    branch_prefix: str = "shipit/deploy-pack",
    title: str = "Drydock: add Deploy Pack (Dockerfile, compose, CI)",
    body: str = "",
    token: str | None = None,
    deletions: list[str] | None = None,
    job_id: str | None = None,
    transport: httpx.BaseTransport | None = None,
) -> PullRequestResult:
    """Open a PR that adds/updates `files` and, optionally, untracks the
    paths in `deletions`.

    A deletion is a tree entry with `sha: null` against the base tree —
    the Git Data API's way to drop a path from the new commit's tree. That
    is exactly `git rm --cached` semantics: the file stops being tracked
    from this commit forward, but history is untouched (no rewrite, no
    force-push) and the owner's local working copy is never deleted. Used
    by the Fix Pack flow to untrack a committed `.env`.

    Idempotency: when `job_id` is given the branch name is derived from it
    (`f"{branch_prefix}-{job_id}"`), which is the only identifier that is
    stable across a retry of the same job — the queue reaper re-runs the
    whole pipeline on a crashed lease, and a content-derived branch would
    change if any generated byte differed, opening a second PR for one
    payment. Before creating anything we ask GitHub whether a PR already
    exists for that branch and, if so, return it untouched. Without a
    `job_id` the branch falls back to the content hash (`commit_sha[:8]`),
    the pre-idempotency behaviour, for callers that have no stable id.
    """
    token = token or token_from_env()
    if not token:
        raise DeliveryError("no GitHub token configured (GITHUB_PR_TOKEN)")

    headers = {**_HEADERS_BASE, "Authorization": f"Bearer {token}"}
    with httpx.Client(base_url=GITHUB_API, headers=headers, timeout=30,
                       transport=transport) as client:
        # Deterministic branch + pre-flight only when we have a stable job
        # id. If a PR already exists for this head (open, merged, or closed),
        # return it and create nothing — this is the idempotency guard.
        deterministic_branch = (
            f"{branch_prefix}-{job_id}" if job_id else None
        )
        if deterministic_branch:
            found = _find_open_pr(client, owner, repo, deterministic_branch)
            if found is not None:
                return found

        base_ref = client.get(f"/repos/{owner}/{repo}/git/ref/heads/{base_branch}")
        _check(base_ref, "resolve base branch")
        base_sha = base_ref.json()["object"]["sha"]

        base_commit = client.get(f"/repos/{owner}/{repo}/git/commits/{base_sha}")
        _check(base_commit, "resolve base commit")
        base_tree_sha = base_commit.json()["tree"]["sha"]

        tree_entries = []
        for path, content in files.items():
            blob = client.post(
                f"/repos/{owner}/{repo}/git/blobs",
                json={"content": content, "encoding": "utf-8"},
            )
            _check(blob, f"create blob for {path}")
            tree_entries.append({
                "path": path, "mode": "100644", "type": "blob",
                "sha": blob.json()["sha"],
            })

        for path in deletions or []:
            # sha: null against base_tree removes the path from the new
            # tree — untrack, not history rewrite.
            tree_entries.append({
                "path": path, "mode": "100644", "type": "blob", "sha": None,
            })

        tree = client.post(
            f"/repos/{owner}/{repo}/git/trees",
            json={"base_tree": base_tree_sha, "tree": tree_entries},
        )
        _check(tree, "create tree")

        commit = client.post(
            f"/repos/{owner}/{repo}/git/commits",
            json={"message": title, "tree": tree.json()["sha"],
                  "parents": [base_sha]},
        )
        _check(commit, "create commit")
        commit_sha = commit.json()["sha"]

        branch = deterministic_branch or f"{branch_prefix}-{commit_sha[:8]}"
        ref = client.post(
            f"/repos/{owner}/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch}", "sha": commit_sha},
        )
        # A prior attempt may have created the branch and then died before
        # opening the PR: "Reference already exists" (422) is not a failure,
        # we just open the PR against the branch that is already there.
        if not _already_exists(ref):
            _check(ref, "create branch")

        pr = client.post(
            f"/repos/{owner}/{repo}/pulls",
            json={"title": title, "head": branch, "base": base_branch, "body": body},
        )
        # A concurrent attempt may have opened the PR between our pre-flight
        # and here: "A pull request already exists" (422) means look it up and
        # return the existing one rather than failing.
        if _already_exists(pr):
            found = _find_open_pr(client, owner, repo, branch)
            if found is not None:
                return found
        _check(pr, "open pull request")

        return PullRequestResult(html_url=pr.json()["html_url"], branch=branch)


def _find_open_pr(
    client: httpx.Client, owner: str, repo: str, branch: str
) -> PullRequestResult | None:
    """Return an existing PR for `branch` (any state), or None. The head
    filter must be `owner:branch`, not the bare branch name."""
    resp = client.get(
        f"/repos/{owner}/{repo}/pulls",
        params={"head": f"{owner}:{branch}", "state": "all"},
    )
    _check(resp, "look up existing pull request")
    prs = resp.json()
    if prs:
        return PullRequestResult(html_url=prs[0]["html_url"], branch=branch)
    return None


def _already_exists(resp: httpx.Response) -> bool:
    """GitHub's 422 for a ref/PR that a prior or concurrent attempt already
    created ("Reference already exists" / "A pull request already exists")."""
    return resp.status_code == 422 and "already exists" in resp.text.lower()


def _check(resp: httpx.Response, action: str) -> None:
    if resp.status_code >= 300:
        raise DeliveryError(f"{action} failed: {resp.status_code} {resp.text[:300]}")
