"""Self-contained HTML report for an audit result.

Every value that originates from the archive or the LLM (file names,
titles, evidence masks) is hostile and is HTML-escaped. No external
assets: the report is a single file that can be shared as-is.
"""

from __future__ import annotations

from html import escape

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
_SEVERITY_COLOR = {
    "critical": "#e5484d", "high": "#f76b15",
    "medium": "#f5d90a", "low": "#8b8d98",
}


def _score_color(total: float) -> str:
    if total >= 8:
        return "#30a46c"
    if total >= 5:
        return "#f5d90a"
    return "#e5484d"


def _bar(label: str, value: float) -> str:
    pct = int(value * 10)
    return (
        f'<div class="cat"><span class="cat-name">{escape(label)}</span>'
        f'<div class="track"><div class="fill" style="width:{pct}%;'
        f'background:{_score_color(value)}"></div></div>'
        f'<span class="cat-val">{value:.1f}</span></div>'
    )


def _finding_row(f: dict) -> str:
    sev = str(f.get("severity", "low"))
    color = _SEVERITY_COLOR.get(sev, "#8b8d98")
    loc = escape(str(f.get("file", "")))
    if f.get("line"):
        loc += f":{int(f['line'])}"
    return (
        '<tr>'
        f'<td><span class="sev" style="background:{color}">{escape(sev)}</span></td>'
        f'<td class="title">{escape(str(f.get("title", "")))}</td>'
        f'<td class="loc">{loc}</td>'
        f'<td class="loc">{escape(str(f.get("masked", "")))}</td>'
        '</tr>'
    )


def render_report(result: dict, project_name: str = "your app") -> str:
    score = result["score"]
    total = float(score["total"])
    findings = sorted(
        result.get("findings", []),
        key=lambda f: (_SEVERITY_ORDER.get(str(f.get("severity")), 9),
                       -float(f.get("confidence", 0))),
    )

    cats = "".join(
        _bar(name, val) for name, val in score["categories"].items()
    )
    if findings:
        rows = "".join(_finding_row(f) for f in findings)
        body = (
            '<table><thead><tr><th></th><th>Finding</th>'
            '<th>Location</th><th>Preview</th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
        )
    else:
        body = '<p class="clean">No issues found by the current checks.</p>'

    counts = {}
    for f in findings:
        counts[f.get("severity")] = counts.get(f.get("severity"), 0) + 1
    summary = " · ".join(
        f"{counts[s]} {s}" for s in ("critical", "high", "medium", "low")
        if s in counts
    ) or "clean"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ShipIt audit — {escape(project_name)}</title>
<meta property="og:title" content="Production Readiness Score: {total:.1f}/10">
<meta property="og:description" content="{escape(summary)} — ShipIt audit of {escape(project_name)}">
<style>
 body{{margin:0;background:#111113;color:#ededef;
      font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif}}
 .wrap{{max-width:860px;margin:0 auto;padding:40px 20px}}
 header{{display:flex;align-items:center;gap:28px;margin-bottom:32px}}
 .ring{{width:110px;height:110px;border-radius:50%;display:flex;
       align-items:center;justify-content:center;flex-shrink:0;
       border:6px solid {_score_color(total)};font-size:30px;font-weight:700}}
 h1{{font-size:20px;margin:0 0 4px}} .sub{{color:#8b8d98;font-size:13px}}
 .cat{{display:flex;align-items:center;gap:10px;margin:6px 0}}
 .cat-name{{width:110px;color:#8b8d98;font-size:13px}}
 .cat-val{{width:34px;text-align:right;font-variant-numeric:tabular-nums}}
 .track{{flex:1;height:8px;background:#26262a;border-radius:4px;overflow:hidden}}
 .fill{{height:100%}}
 table{{width:100%;border-collapse:collapse;margin-top:24px;font-size:14px}}
 th{{text-align:left;color:#8b8d98;font-weight:500;font-size:12px;
    padding:6px 10px;border-bottom:1px solid #26262a}}
 td{{padding:8px 10px;border-bottom:1px solid #1c1c1f;vertical-align:top}}
 .sev{{padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;
      color:#111113;text-transform:uppercase}}
 .loc{{font-family:ui-monospace,Menlo,monospace;font-size:12px;color:#8b8d98}}
 .clean{{color:#30a46c}}
 footer{{margin-top:36px;color:#5a5c66;font-size:12px}}
</style></head><body><div class="wrap">
<header>
  <div class="ring">{total:.1f}</div>
  <div>
    <h1>Production Readiness — {escape(project_name)}</h1>
    <div class="sub">stack: {escape(str(result.get("stack", "?")))} · {escape(summary)}</div>
  </div>
</header>
<section>{cats}</section>
{body}
<footer>Generated by ShipIt — free audit, verified fixes as pull requests.</footer>
</div></body></html>"""
