"""How often can a static RLS scan see anything at all? Measured on n≈190.

WHY THIS EXISTS. SUPABASE_RLS_YIELD_PLAN.md's Part A found that 3 of 7
Supabase-using repos commit no schema — "undetermined, not secure", the
population the live probe exists for. Three out of seven is not a rate. Its
95% interval runs from 16% to 84%, which spans "static analysis covers most of
this market" and "static analysis covers almost none of it", and those two
worlds want different products. This script replaces that 7 with a number big
enough to distinguish them.

IT MEASURES ONE THING: given a vibe-coded repository that uses Supabase, does
it commit its schema? That is the coverage question. Everything else here —
which tables look private, which are anon-readable — is computed with the
SHIPPED detector (app.scan.rls) and reported as a secondary read, because the
detector is already written and running it over 190 repos costs nothing extra.

WHAT IT IS NOT. It is not a prevalence rate for the vibe-coded population as a
whole. The sample is drawn from repositories carrying `lovable-tagger`, so
every number here is conditional on "generated by Lovable", and the corpus in
measure_supabase_rls_yield.py (9 repos, chosen in July for an unrelated CORS
experiment) remains the only unfiltered one. The two are reported separately
and must not be pooled: one is a random-ish slice of vibe-coded repos, the
other is a slice of one generator's output.

NO LIVE CONTACT. Nothing here queries a Supabase project. The hard constraint
from the plan — the measurement must not read rows from a project we do not
own — is satisfied structurally: the only network calls are git fetches of
public repositories.

SAMPLING, STATED BECAUSE IT IS NOT RANDOM. GitHub code search, query
`"lovable-tagger" filename:package.json`, pages 1-2 in the order returned,
fetched 2026-08-18, deduped by repository. GitHub's relevance ordering is not
a uniform sample and there is no way to draw one; what can be said is that
nothing in the ranking is plausibly correlated with whether a repo commits
migrations, which is the only quantity at stake. Search is used for DISCOVERY
only — membership in the corpus is re-decided by reading the repository's own
package.json out of the pinned tree, so a stale or wrong search hit drops out
rather than counting.

Usage:
    python scripts/measure_rls_blind_spot.py
    LIMIT=20 python scripts/measure_rls_blind_spot.py      # a quick pass
    WORKERS=4 python scripts/measure_rls_blind_spot.py
    KEEP=1 python scripts/measure_rls_blind_spot.py        # keep the clones

Writes batch_reports/rls_blind_spot.json — one record per repository, pinned to
the SHA that was read, so the run can be reproduced or disputed.
"""

from __future__ import annotations

import io
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.scan.rls import (  # noqa: E402
    RULE_ID,
    WRITE_RULE_ID,
    _SCHEMA_PATH_HINTS,
    scan_rls,
)

ROOT = Path(__file__).resolve().parent.parent
# Tracked, because it is an INPUT: the run cannot be reproduced or disputed
# without the list it drew from. The result JSON goes to batch_reports/, which
# is gitignored, like every other measurement output here.
CANDIDATES = ROOT / "scripts" / "data" / "lovable_candidates.txt"
OUT = ROOT / "batch_reports" / "rls_blind_spot.json"

# The marker that decides membership, checked against the repo rather than
# against the search result that suggested it.
GENERATOR_MARKER = "lovable-tagger"

# `@supabase/supabase-js` in a package.json is the load-bearing signal: it is
# the client the anon key is handed to. A `supabase/` directory alone is
# weaker — it can hold only edge functions or a config.toml — so it is recorded
# separately rather than folded in.
SUPABASE_DEP = "@supabase/supabase-js"

_CLONE_TIMEOUT_S = 120
_SHOW_TIMEOUT_S = 60


@dataclass
class Repo:
    slug: str
    sha: str = ""
    reachable: bool = False
    error: str = ""

    is_lovable: bool = False
    has_supabase_dep: bool = False
    has_supabase_dir: bool = False
    sql_paths: list[str] = field(default_factory=list)
    schema_paths: list[str] = field(default_factory=list)

    read_findings: list[str] = field(default_factory=list)
    write_findings: list[str] = field(default_factory=list)

    @property
    def uses_supabase(self) -> bool:
        return self.has_supabase_dep

    @property
    def commits_schema(self) -> bool:
        return bool(self.schema_paths)


def _git(args: list[str], cwd: str | None = None,
         timeout: int = _SHOW_TIMEOUT_S) -> subprocess.CompletedProcess:
    """Decoded by us, not by subprocess, with errors replaced.

    `text=True` decodes as strict UTF-8 and raises on anything else. A survey
    of strangers' repositories will meet a UTF-16 migration eventually — one
    did, at repo ~120 of 199 — and a decode error inside a worker killed the
    entire run. The same file is what the shipped detector reads, and it
    decodes with errors="replace"; matching that here keeps the measurement
    reading exactly what production reads, mojibake included.
    """
    proc = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True,
        timeout=timeout, check=False,
    )
    return subprocess.CompletedProcess(
        proc.args, proc.returncode,
        proc.stdout.decode("utf-8", errors="replace"),
        proc.stderr.decode("utf-8", errors="replace"),
    )


def _is_schema_file(path: str) -> bool:
    """The SAME rule the shipped detector uses, so the measurement's
    denominator and the product's blind spot are the same set.

    read_committed_sql keeps a .sql file when its path carries a schema hint or
    when it sits at the repository root. Duplicating the condition here rather
    than importing a private helper would be the two-readers problem this
    project already paid for once (see app/scan/sql_schema.py), so the hint
    tuple itself is imported.
    """
    if not path.lower().endswith(".sql"):
        return False
    return any(h in path.lower() for h in _SCHEMA_PATH_HINTS) or "/" not in path


def inspect(slug: str, workdir: Path) -> Repo:
    """One repository, and never more than one.

    ONE REPOSITORY MUST NOT BE ABLE TO END THE RUN. The first full pass died
    at repo ~120 of 199 on a UTF-16 `.sql` file, and 119 completed inspections
    went with it. The decode is fixed below, but the shape of that failure is
    the thing worth guarding: a survey of strangers' repositories will keep
    meeting inputs nobody predicted, and each one belongs in a record with a
    reason, excluded from every denominator — exactly how an unreachable repo
    is already treated.
    """
    try:
        return _inspect(slug, workdir)
    except Exception as exc:                      # noqa: BLE001
        return Repo(slug=slug, error=f"{type(exc).__name__}: {exc}"[:200])


def _inspect(slug: str, workdir: Path) -> Repo:
    """Read through a blobless partial clone.

    `--filter=blob:none --no-checkout` fetches commits and trees but no file
    contents: enough to list every path for a couple of hundred kilobytes, with
    the handful of files we actually read fetched on demand. A full clone of
    the same repository is tens of megabytes, and 199 of those is a different
    kind of script.
    """
    repo = Repo(slug=slug)
    dest = workdir / slug.replace("/", "__")
    proc = _git([
        "clone", "--filter=blob:none", "--no-checkout", "--depth", "1",
        f"https://github.com/{slug}", str(dest),
    ], timeout=_CLONE_TIMEOUT_S)
    if proc.returncode != 0:
        repo.error = (proc.stderr or "clone failed").strip().splitlines()[-1][:200]
        return repo

    head = _git(["rev-parse", "HEAD"], cwd=str(dest))
    if head.returncode != 0:
        repo.error = "no HEAD"
        return repo
    repo.sha = head.stdout.strip()
    repo.reachable = True

    listing = _git(["ls-tree", "-r", "HEAD", "--name-only"], cwd=str(dest))
    if listing.returncode != 0:
        repo.reachable = False
        repo.error = "ls-tree failed"
        return repo
    paths = [p for p in listing.stdout.splitlines() if p]

    # MEMBERSHIP is read from any package.json VARIANT — `package.json.bak`,
    # `.old`, `.backup` — and from the README. A repo whose manifest was later
    # hand-edited is still a Lovable repo, and dropping those would select for
    # untouched scaffolding, which is plausibly the half LEAST likely to have
    # acquired committed migrations. That is a bias pointing straight at the
    # quantity being measured.
    #
    # THE SUPABASE DEPENDENCY is read only from a current `package.json`. Here
    # the stale copy is the wrong evidence in the other direction: a backup
    # proves what the project used to use, and this asks what it uses.
    manifests = [p for p in paths if p.rsplit("/", 1)[-1].startswith("package.json")]
    for manifest in manifests[:12]:
        shown = _git(["show", f"HEAD:{manifest}"], cwd=str(dest))
        if shown.returncode != 0:
            continue
        text = shown.stdout
        if GENERATOR_MARKER in text:
            repo.is_lovable = True
        if SUPABASE_DEP in text and manifest.rsplit("/", 1)[-1] == "package.json":
            repo.has_supabase_dep = True

    if not repo.is_lovable:
        for readme in [p for p in paths
                       if p.rsplit("/", 1)[-1].lower().startswith("readme")][:3]:
            shown = _git(["show", f"HEAD:{readme}"], cwd=str(dest))
            if shown.returncode == 0 and "lovable.dev" in shown.stdout.lower():
                repo.is_lovable = True
                break

    repo.has_supabase_dir = any(p.startswith("supabase/") for p in paths)
    repo.sql_paths = [p for p in paths if p.lower().endswith(".sql")]
    repo.schema_paths = [p for p in repo.sql_paths if _is_schema_file(p)]

    if repo.schema_paths:
        _run_detector(repo, dest)

    return repo


def _run_detector(repo: Repo, dest: Path) -> None:
    """Run the SHIPPED detector over the committed SQL.

    Built as an in-memory zip because that is the interface production uses.
    Reimplementing the scan against a directory would give this script its own
    copy of the classification, and a measurement that disagrees with the
    product about the same table is the failure this project has already
    written down twice.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for path in repo.schema_paths[:200]:
            shown = _git(["show", f"HEAD:{path}"], cwd=str(dest))
            if shown.returncode != 0:
                continue
            zf.writestr(f"{repo.slug.split('/')[-1]}/{path}", shown.stdout)
    buf.seek(0)
    try:
        findings = scan_rls(buf)
    except Exception as exc:                      # noqa: BLE001
        repo.error = f"detector: {type(exc).__name__}: {exc}"[:200]
        return
    repo.read_findings = [f.title for f in findings if f.rule_id == RULE_ID]
    repo.write_findings = [f.title for f in findings if f.rule_id == WRITE_RULE_ID]


def wilson(hits: int, total: int) -> tuple[float, float]:
    """95% confidence interval for a proportion.

    Printed next to every rate because the entire point of this run is that
    3-of-7 was a number without one. Wilson rather than the textbook normal
    interval: at the sample sizes further down the funnel the normal interval
    runs past 0 and 1, which reads as certainty about the impossible.
    """
    if total == 0:
        return (0.0, 0.0)
    z = 1.959964
    p = hits / total
    denom = 1 + z * z / total
    centre = (p + z * z / (2 * total)) / denom
    margin = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denom
    return (max(0.0, centre - margin), min(1.0, centre + margin))


def _rate(hits: int, total: int) -> str:
    if total == 0:
        return "n/a (no denominator)"
    low, high = wilson(hits, total)
    return (f"{hits}/{total} = {100 * hits / total:.0f}% "
            f"[95% CI {100 * low:.0f}-{100 * high:.0f}%]")


def load_candidates() -> list[str]:
    slugs: list[str] = []
    seen: set[str] = set()
    for line in CANDIDATES.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line in seen:
            continue
        seen.add(line)
        slugs.append(line)
    return slugs


def main() -> int:
    slugs = load_candidates()
    limit = int(os.environ.get("LIMIT", "0")) or len(slugs)
    slugs = slugs[:limit]
    workers = int(os.environ.get("WORKERS", "8"))
    keep = os.environ.get("KEEP") == "1"

    workdir = Path(tempfile.mkdtemp(prefix="rls-blind-spot-"))
    print(f"{len(slugs)} candidate repos, {workers} workers, clones in {workdir}\n")
    try:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            repos = list(pool.map(lambda s: inspect(s, workdir), slugs))
    finally:
        if not keep:
            shutil.rmtree(workdir, ignore_errors=True)

    unreachable = [r for r in repos if not r.reachable]
    reachable = [r for r in repos if r.reachable]
    # Membership decided by the repository, not by the search that found it.
    lovable = [r for r in reachable if r.is_lovable]
    supa = [r for r in lovable if r.uses_supabase]
    with_schema = [r for r in supa if r.commits_schema]
    blind = [r for r in supa if not r.commits_schema]
    exposed_read = [r for r in with_schema if r.read_findings]
    exposed_write = [r for r in with_schema if r.write_findings]

    print("=" * 72)
    print("FUNNEL")
    print("=" * 72)
    print(f"candidates from search           : {len(slugs)}")
    print(f"  not inspected (gone / failed)  : {len(unreachable)}"
          "   <- excluded from every denominator below")
    print(f"  reachable                      : {len(reachable)}")
    print(f"    carries {GENERATOR_MARKER:<22}: {len(lovable)}"
          "   <- the corpus, verified in-repo")
    print(f"      uses {SUPABASE_DEP:<23}: {_rate(len(supa), len(lovable))}")
    print(f"        commits its schema       : {_rate(len(with_schema), len(supa))}")
    print(f"        commits NO schema        : {_rate(len(blind), len(supa))}"
          "   <- THE BLIND SPOT")
    print()
    print("Within the repos whose schema can be read — secondary, and a "
          "statement about\nrepositories rather than deployments (Part C, n=1, "
          "found the two disagree):")
    print(f"  a private-shaped table is anon-readable : "
          f"{_rate(len(exposed_read), len(with_schema))}")
    print(f"  a table is anon-writable                : "
          f"{_rate(len(exposed_write), len(with_schema))}")

    if unreachable:
        print(f"\nNot inspected ({len(unreachable)}) — deleted, renamed, or "
              "something this reader\ncould not handle. Excluded rather than "
              "counted as anything:")
        for r in unreachable[:15]:
            print(f"  {r.slug}: {r.error}")
        if len(unreachable) > 15:
            print(f"  … and {len(unreachable) - 15} more")

    dropped = [r for r in reachable if not r.is_lovable]
    if dropped:
        print(f"\nSearch hits that are not Lovable repos ({len(dropped)}) — "
              "dropped on\nre-verification, which is what re-verification is "
              "for:")
        for r in dropped[:10]:
            print(f"  {r.slug}")
        if len(dropped) > 10:
            print(f"  … and {len(dropped) - 10} more")

    # A repo with a supabase/ directory but no committed SQL is the blind spot
    # in its clearest form: the developer used the CLI or the dashboard, and the
    # schema lives only in the project.
    dir_no_sql = [r for r in blind if r.has_supabase_dir]
    print(f"\nOf the {len(blind)} blind-spot repos, {len(dir_no_sql)} carry a "
          "`supabase/` directory\nwith no schema SQL in it — configured "
          "against a live project whose tables\nwere never written down here.")

    if exposed_read or exposed_write:
        print("\nRepos where the committed SQL describes an open table:")
        for r in with_schema:
            if r.read_findings or r.write_findings:
                print(f"  {r.slug}  read={len(r.read_findings)} "
                      f"write={len(r.write_findings)}")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps({
        "query": '"lovable-tagger" filename:package.json (pages 1-2, 2026-08-18)',
        "candidates": len(slugs),
        "unreachable": len(unreachable),
        "lovable": len(lovable),
        "uses_supabase": len(supa),
        "commits_schema": len(with_schema),
        "blind_spot": len(blind),
        "blind_spot_ci": wilson(len(blind), len(supa)),
        "anon_readable": len(exposed_read),
        "anon_writable": len(exposed_write),
        "repos": [asdict(r) for r in repos],
    }, indent=2))
    print(f"\nwrote {OUT}")

    if len(supa) < 25:
        print("\nREFUSING TO REPORT A RATE: fewer than 25 Supabase repos "
              "reached.\nThe interval would be as useless as the 3-of-7 this "
              "run exists to replace.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
