"""How often can a static RLS scan see anything at all? Measured on n≈190.

WHY THIS EXISTS. SUPABASE_RLS_YIELD_PLAN.md's Part A found that 3 of 7
Supabase-using repos commit no schema — "undetermined, not secure", the
population the live probe exists for. Three out of seven is not a rate. Its
95% interval runs from 16% to 84%, which spans "static analysis covers most of
this market" and "static analysis covers almost none of it", and those two
worlds want different products. This script replaces that 7 with a number big
enough to distinguish them.

IT MEASURES ONE THING: given a vibe-coded repository that uses Supabase, does
it commit its schema? That is the coverage question. Everything else here —
which tables look private, which are anon-readable — is computed with the
SHIPPED detector (app.scan.rls) and reported as a secondary read, because the
detector is already written and running it over 190 repos costs nothing extra.

WHAT IT IS NOT. It is not a prevalence rate for the vibe-coded population as a
whole. The sample is drawn from repositories carrying `lovable-tagger`, so
every number here is conditional on "generated by Lovable", and the corpus in
measure_supabase_rls_yield.py (9 repos, chosen in July for an unrelated CORS
experiment) remains the only unfiltered one. The two are reported separately
and must not be pooled: one is a random-ish slice of vibe-coded repos, the
other is a slice of one generator's output.

NO LIVE CONTACT. Nothing here queries a Supabase project. The hard constraint
from the plan — the measurement must not read rows from a project we do not
own — is satisfied structurally: the only network calls are git fetches of
public repositories.

SAMPLING, STATED BECAUSE IT IS NOT RANDOM. GitHub code search, query
`"lovable-tagger" filename:package.json`, pages 1-2 in the order returned,
fetched 2026-08-18, deduped by repository. GitHub's relevance ordering is not
a uniform sample and there is no way to draw one; what can be said is that
nothing in the ranking is plausibly correlated with whether a repo commits
migrations, which is the only quantity at stake. Search is used for DISCOVERY
only — membership in the corpus is re-decided by reading the repository's own
package.json out of the pinned tree, so a stale or wrong search hit drops out
rather than counting.

Usage:
    python scripts/measure_rls_blind_spot.py
    LIMIT=20 python scripts/measure_rls_blind_spot.py      # a quick pass
    WORKERS=4 python scripts/measure_rls_blind_spot.py
    KEEP=1 python scripts/measure_rls_blind_spot.py        # keep the clones

Writes batch_reports/rls_blind_spot.json — one record per repository, pinned to
the SHA that was read, so the run can be reproduced or disputed.
"""

from __future__ import annotations

import io
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.scan.rls import (  # noqa: E402
    RULE_ID,
    WRITE_RULE_ID,
    _SCHEMA_PATH_HINTS,
    scan_rls,
)

ROOT = Path(__file__).resolve().parent.parent
# Tracked, because they are INPUTS: a run cannot be reproduced or disputed
# without the list it drew from, and GitHub's code search is not reachable from
# the script (the session proxy allows only repository-scoped API paths), so
# these lists are captured artefacts rather than something the script can
# regenerate. The result JSON goes to batch_reports/, which is gitignored, like
# every other measurement output here.
DATA = ROOT / "scripts" / "data"
OUT = ROOT / "batch_reports" / "rls_blind_spot.json"

# `@supabase/supabase-js` in a package.json is the load-bearing signal: it is
# the client the anon key is handed to. A `supabase/` directory alone is
# weaker — it can hold only edge functions or a config.toml — so it is recorded
# separately rather than folded in.
SUPABASE_DEP = "@supabase/supabase-js"

# Markers that identify a generator, checked against the repository rather than
# against the search result that suggested it. `lovable-tagger` is a build
# plugin in package.json; `.bolt/` is bolt's own scaffolding directory; the v0
# marker is included so the control stratum can exclude it, not because v0 is
# measured here.
LOVABLE_MARKERS = ("lovable-tagger", "lovable.dev")
BOLT_DIR = ".bolt/"
V0_MARKERS = ("v0.dev", "v0-user-next.config")


@dataclass(frozen=True)
class Stratum:
    """One population, its candidate list, and how membership is decided.

    THE THREE ARE NOT POOLED, and the reason is in the entry criteria. Lovable
    and bolt are drawn on a GENERATOR marker, so "uses Supabase" is a funnel
    stage inside them and its rate means something. The control is drawn on the
    Supabase dependency itself, so that rate is how the sample was built and is
    not a finding. The conditional rate — given Supabase, is the schema
    committed — is the same question in all three, which is why it is the one
    being compared.
    """

    key: str
    label: str
    candidates: str
    # Whether "uses Supabase" was the entry criterion rather than a stage.
    supabase_is_entry: bool = False


STRATA = (
    Stratum("lovable", "Lovable (`lovable-tagger`)", "lovable_candidates.txt"),
    Stratum("bolt", "bolt (`.bolt/` scaffolding)", "bolt_candidates.txt"),
    Stratum("handwritten", "no generator marker (control)",
            "handwritten_candidates.txt", supabase_is_entry=True),
)

_CLONE_TIMEOUT_S = 120
_SHOW_TIMEOUT_S = 60


@dataclass
class Repo:
    slug: str
    stratum: str = ""
    sha: str = ""
    reachable: bool = False
    error: str = ""

    is_lovable: bool = False
    is_bolt: bool = False
    is_v0: bool = False
    has_supabase_dep: bool = False
    has_supabase_dir: bool = False
    sql_paths: list[str] = field(default_factory=list)
    schema_paths: list[str] = field(default_factory=list)
    # Tables named by a `supabase gen types typescript` file, which is
    # generated FROM THE LIVE PROJECT and can therefore name a table that has
    # no migration — the measured gap this field exists to size.
    types_files: list[str] = field(default_factory=list)
    types_tables: list[str] = field(default_factory=list)

    read_findings: list[str] = field(default_factory=list)
    write_findings: list[str] = field(default_factory=list)

    @property
    def uses_supabase(self) -> bool:
        return self.has_supabase_dep

    @property
    def commits_schema(self) -> bool:
        return bool(self.schema_paths)

    def belongs_to(self, stratum: Stratum) -> bool:
        """Is this repository a member of the stratum it was drawn for?

        The control is defined by ABSENCE, so it carries the exclusions: a
        repository found by searching for the Supabase dependency may still
        turn out to be Lovable or bolt output, and leaving it in would blur
        the only comparison the control exists to make.
        """
        if stratum.key == "lovable":
            return self.is_lovable
        if stratum.key == "bolt":
            return self.is_bolt
        return not (self.is_lovable or self.is_bolt or self.is_v0)


def _git(args: list[str], cwd: str | None = None,
         timeout: int = _SHOW_TIMEOUT_S) -> subprocess.CompletedProcess:
    """Decoded by us, not by subprocess, with errors replaced.

    `text=True` decodes as strict UTF-8 and raises on anything else. A survey
    of strangers' repositories will meet a UTF-16 migration eventually — one
    did, at repo ~120 of 199 — and a decode error inside a worker killed the
    entire run. The same file is what the shipped detector reads, and it
    decodes with errors="replace"; matching that here keeps the measurement
    reading exactly what production reads, mojibake included.
    """
    proc = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True,
        timeout=timeout, check=False,
    )
    return subprocess.CompletedProcess(
        proc.args, proc.returncode,
        proc.stdout.decode("utf-8", errors="replace"),
        proc.stderr.decode("utf-8", errors="replace"),
    )


def _is_schema_file(path: str) -> bool:
    """The SAME rule the shipped detector uses, so the measurement's
    denominator and the product's blind spot are the same set.

    read_committed_sql keeps a .sql file when its path carries a schema hint or
    when it sits at the repository root. Duplicating the condition here rather
    than importing a private helper would be the two-readers problem this
    project already paid for once (see app/scan/sql_schema.py), so the hint
    tuple itself is imported.
    """
    if not path.lower().endswith(".sql"):
        return False
    return any(h in path.lower() for h in _SCHEMA_PATH_HINTS) or "/" not in path


def inspect(slug: str, workdir: Path) -> Repo:
    """One repository, and never more than one.

    ONE REPOSITORY MUST NOT BE ABLE TO END THE RUN. The first full pass died
    at repo ~120 of 199 on a UTF-16 `.sql` file, and 119 completed inspections
    went with it. The decode is fixed below, but the shape of that failure is
    the thing worth guarding: a survey of strangers' repositories will keep
    meeting inputs nobody predicted, and each one belongs in a record with a
    reason, excluded from every denominator — exactly how an unreachable repo
    is already treated.
    """
    try:
        return _inspect(slug, workdir)
    except Exception as exc:                      # noqa: BLE001
        return Repo(slug=slug, error=f"{type(exc).__name__}: {exc}"[:200])


def _inspect(slug: str, workdir: Path) -> Repo:
    """Read through a blobless partial clone.

    `--filter=blob:none --no-checkout` fetches commits and trees but no file
    contents: enough to list every path for a couple of hundred kilobytes, with
    the handful of files we actually read fetched on demand. A full clone of
    the same repository is tens of megabytes, and 199 of those is a different
    kind of script.
    """
    repo = Repo(slug=slug)
    dest = workdir / slug.replace("/", "__")
    proc = _git([
        "clone", "--filter=blob:none", "--no-checkout", "--depth", "1",
        f"https://github.com/{slug}", str(dest),
    ], timeout=_CLONE_TIMEOUT_S)
    if proc.returncode != 0:
        repo.error = (proc.stderr or "clone failed").strip().splitlines()[-1][:200]
        return repo

    head = _git(["rev-parse", "HEAD"], cwd=str(dest))
    if head.returncode != 0:
        repo.error = "no HEAD"
        return repo
    repo.sha = head.stdout.strip()
    repo.reachable = True

    listing = _git(["ls-tree", "-r", "HEAD", "--name-only"], cwd=str(dest))
    if listing.returncode != 0:
        repo.reachable = False
        repo.error = "ls-tree failed"
        return repo
    paths = [p for p in listing.stdout.splitlines() if p]

    # MEMBERSHIP is read from any package.json VARIANT — `package.json.bak`,
    # `.old`, `.backup` — and from the README. A repo whose manifest was later
    # hand-edited is still a Lovable repo, and dropping those would select for
    # untouched scaffolding, which is plausibly the half LEAST likely to have
    # acquired committed migrations. That is a bias pointing straight at the
    # quantity being measured.
    #
    # THE SUPABASE DEPENDENCY is read only from a current `package.json`. Here
    # the stale copy is the wrong evidence in the other direction: a backup
    # proves what the project used to use, and this asks what it uses.
    manifests = [p for p in paths if p.rsplit("/", 1)[-1].startswith("package.json")]
    for manifest in manifests[:12]:
        shown = _git(["show", f"HEAD:{manifest}"], cwd=str(dest))
        if shown.returncode != 0:
            continue
        text = shown.stdout
        lowered = text.lower()
        if any(m in lowered for m in LOVABLE_MARKERS):
            repo.is_lovable = True
        if any(m in lowered for m in V0_MARKERS):
            repo.is_v0 = True
        if SUPABASE_DEP in text and manifest.rsplit("/", 1)[-1] == "package.json":
            repo.has_supabase_dep = True

    # bolt is decided by its scaffolding directory, which is in the tree and
    # needs no blob fetched. Structural rather than a string in a manifest
    # somebody may have rewritten.
    repo.is_bolt = any(p.startswith(BOLT_DIR) for p in paths)

    if not (repo.is_lovable or repo.is_v0):
        for readme in [p for p in paths
                       if p.rsplit("/", 1)[-1].lower().startswith("readme")][:3]:
            shown = _git(["show", f"HEAD:{readme}"], cwd=str(dest))
            if shown.returncode != 0:
                continue
            lowered = shown.stdout.lower()
            if any(m in lowered for m in LOVABLE_MARKERS):
                repo.is_lovable = True
            if any(m in lowered for m in V0_MARKERS):
                repo.is_v0 = True
            if repo.is_lovable or repo.is_v0:
                break

    _read_generated_types(repo, dest, paths)
    repo.has_supabase_dir = any(p.startswith("supabase/") for p in paths)
    repo.sql_paths = [p for p in paths if p.lower().endswith(".sql")]
    repo.schema_paths = [p for p in repo.sql_paths if _is_schema_file(p)]

    if repo.schema_paths:
        _run_detector(repo, dest)

    return repo


def _run_detector(repo: Repo, dest: Path) -> None:
    """Run the SHIPPED detector over the committed SQL.

    Built as an in-memory zip because that is the interface production uses.
    Reimplementing the scan against a directory would give this script its own
    copy of the classification, and a measurement that disagrees with the
    product about the same table is the failure this project has already
    written down twice.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for path in repo.schema_paths[:200]:
            shown = _git(["show", f"HEAD:{path}"], cwd=str(dest))
            if shown.returncode != 0:
                continue
            zf.writestr(f"{repo.slug.split('/')[-1]}/{path}", shown.stdout)
    buf.seek(0)
    try:
        findings = scan_rls(buf)
    except Exception as exc:                      # noqa: BLE001
        repo.error = f"detector: {type(exc).__name__}: {exc}"[:200]
        return
    repo.read_findings = [f.title for f in findings if f.rule_id == RULE_ID]
    repo.write_findings = [f.title for f in findings if f.rule_id == WRITE_RULE_ID]



# Every table entry in a `supabase gen types typescript` file is an identifier
# whose object opens with `Row:`. Matching on that rather than on the file's
# name is what keeps this from depending on where somebody put it.
_TYPES_TABLE = re.compile(r"(\w+):\s*\{\s*Row:")

# Only files whose NAME suggests generated types are read. In a blobless clone
# every file read is a fetch, and reading all TypeScript in every repository to
# find one file would cost more than the question is worth. The consequence is
# stated rather than hidden: a generated types file under an unusual name is
# missed, so this number is a LOWER bound.
_TYPES_NAME_HINTS = ("types", "database", "supabase", "schema")


def _read_generated_types(repo: Repo, dest: Path, paths: list[str]) -> None:
    candidates = [
        p for p in paths
        if p.lower().endswith((".ts", ".tsx"))
        and any(h in p.rsplit("/", 1)[-1].lower() for h in _TYPES_NAME_HINTS)
    ]
    for path in candidates[:12]:
        shown = _git(["show", f"HEAD:{path}"], cwd=str(dest))
        if shown.returncode != 0 or "Row:" not in shown.stdout:
            continue
        found = sorted({m.group(1).lower()
                        for m in _TYPES_TABLE.finditer(shown.stdout)})
        if not found:
            continue
        repo.types_files.append(path)
        for name in found:
            if name not in repo.types_tables:
                repo.types_tables.append(name)


def wilson(hits: int, total: int) -> tuple[float, float]:
    """95% confidence interval for a proportion.

    Printed next to every rate because the entire point of this run is that
    3-of-7 was a number without one. Wilson rather than the textbook normal
    interval: at the sample sizes further down the funnel the normal interval
    runs past 0 and 1, which reads as certainty about the impossible.
    """
    if total == 0:
        return (0.0, 0.0)
    z = 1.959964
    p = hits / total
    denom = 1 + z * z / total
    centre = (p + z * z / (2 * total)) / denom
    margin = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denom
    return (max(0.0, centre - margin), min(1.0, centre + margin))


def _rate(hits: int, total: int) -> str:
    if total == 0:
        return "n/a (no denominator)"
    low, high = wilson(hits, total)
    return (f"{hits}/{total} = {100 * hits / total:.0f}% "
            f"[95% CI {100 * low:.0f}-{100 * high:.0f}%]")


def load_candidates(filename: str) -> list[str]:
    slugs: list[str] = []
    seen: set[str] = set()
    for line in (DATA / filename).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line in seen:
            continue
        seen.add(line)
        slugs.append(line)
    return slugs


def two_proportion_p(hits_a: int, n_a: int, hits_b: int, n_b: int) -> float:
    """Two-sided p for "these two rates are the same", normal approximation.

    Printed so a difference between strata is not read off two overlapping
    intervals by eye. Overlapping 95% intervals do NOT imply no difference, and
    non-overlapping ones are a stricter test than the comparison actually needs
    — either way, eyeballing them is how a survey acquires a conclusion its
    numbers do not support.
    """
    if n_a == 0 or n_b == 0:
        return 1.0
    pooled = (hits_a + hits_b) / (n_a + n_b)
    se = math.sqrt(pooled * (1 - pooled) * (1 / n_a + 1 / n_b))
    if se == 0:
        return 1.0
    z = abs(hits_a / n_a - hits_b / n_b) / se
    return math.erfc(z / math.sqrt(2))


@dataclass
class Result:
    stratum: Stratum
    repos: list[Repo]

    @property
    def unreachable(self) -> list[Repo]:
        return [r for r in self.repos if not r.reachable]

    @property
    def members(self) -> list[Repo]:
        return [r for r in self.repos
                if r.reachable and r.belongs_to(self.stratum)]

    @property
    def supa(self) -> list[Repo]:
        return [r for r in self.members if r.uses_supabase]

    @property
    def with_schema(self) -> list[Repo]:
        return [r for r in self.supa if r.commits_schema]

    @property
    def blind(self) -> list[Repo]:
        return [r for r in self.supa if not r.commits_schema]


def run_stratum(stratum: Stratum, workers: int, limit: int,
                keep: bool) -> Result:
    slugs = load_candidates(stratum.candidates)[:limit] if limit \
        else load_candidates(stratum.candidates)
    workdir = Path(tempfile.mkdtemp(prefix=f"rls-{stratum.key}-"))
    print(f"[{stratum.key}] {len(slugs)} candidates, clones in {workdir}")
    try:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            repos = list(pool.map(lambda s: inspect(s, workdir), slugs))
    finally:
        if not keep:
            shutil.rmtree(workdir, ignore_errors=True)
    for repo in repos:
        repo.stratum = stratum.key
    return Result(stratum, repos)


def report(result: Result) -> None:
    stratum, s = result.stratum, result
    print("\n" + "=" * 72)
    print(f"{stratum.label}")
    print("=" * 72)
    print(f"candidates from search          : {len(s.repos)}")
    print(f"  not inspected (gone / failed) : {len(s.unreachable)}"
          "   <- excluded from every denominator")
    print(f"  members, verified in-repo     : {len(s.members)}")
    if stratum.supabase_is_entry:
        print(f"    uses Supabase               : {len(s.supa)}"
              "   <- the entry criterion, not a finding")
    else:
        print(f"    uses Supabase               : "
              f"{_rate(len(s.supa), len(s.members))}")
    print(f"      commits its schema        : "
          f"{_rate(len(s.with_schema), len(s.supa))}")
    print(f"      commits NO schema         : {_rate(len(s.blind), len(s.supa))}"
          "   <- THE BLIND SPOT")

    read_hits = [r for r in s.with_schema if r.read_findings]
    write_hits = [r for r in s.with_schema if r.write_findings]
    print(f"  anon-readable private table   : "
          f"{_rate(len(read_hits), len(s.with_schema))}")
    print(f"  anon-writable table           : "
          f"{_rate(len(write_hits), len(s.with_schema))}")

    dir_no_sql = [r for r in s.blind if r.has_supabase_dir]
    print(f"  of the blind, carry `supabase/` with no SQL in it: "
          f"{len(dir_no_sql)}/{len(s.blind)}")

    dropped = [r for r in s.repos if r.reachable and not r.belongs_to(stratum)]
    if dropped:
        shown = ", ".join(r.slug for r in dropped[:6])
        print(f"  not members ({len(dropped)}), dropped on re-verification: "
              f"{shown}{' …' if len(dropped) > 6 else ''}")


def main() -> int:
    limit = int(os.environ.get("LIMIT", "0"))
    workers = int(os.environ.get("WORKERS", "8"))
    keep = os.environ.get("KEEP") == "1"
    wanted = os.environ.get("STRATUM", "")
    strata = [s for s in STRATA if not wanted or s.key == wanted]

    results = [run_stratum(s, workers, limit, keep) for s in strata]

    # ONE REPOSITORY FAILING IS THEIRS; ALL OF THEM FAILING THE SAME WAY IS
    # OURS. The per-repo guard that stops a single bad input from ending the
    # run also turns a programming error into a plausible dataset: a NameError
    # in this file once produced 199 "not inspected" repositories and a funnel
    # of zeros that read like a finding. A run is not a measurement if the
    # thing being measured never ran.
    for result in results:
        failures = [r.error for r in result.repos if r.error]
        if failures and len(failures) == len(result.repos) and \
                len(set(failures)) == 1:
            print(f"\n!! every repository in `{result.stratum.key}` failed "
                  f"identically:\n   {failures[0]}\n"
                  f"   That is this script, not those repositories. "
                  f"No number below is a measurement.")
            return 2

    for result in results:
        report(result)

    print("\n" + "=" * 72)
    print("THE COMPARISON: given Supabase, is the schema committed?")
    print("=" * 72)
    for result in results:
        print(f"  {result.stratum.label:<34} "
              f"{_rate(len(result.with_schema), len(result.supa))}")

    pairs = [(a, b) for i, a in enumerate(results) for b in results[i + 1:]]
    if pairs:
        # THE THRESHOLD MOVES WITH THE NUMBER OF QUESTIONS ASKED. Three
        # pairwise tests at 0.05 each carry a 14% chance of at least one false
        # positive when nothing differs at all, so one p just under 0.05 out of
        # three is the expected amount of noise rather than a result. Printing
        # the plain 0.05 verdict beside three comparisons is how a survey
        # announces a difference it did not find.
        threshold = 0.05 / len(pairs)
        print(f"\nDifferences. {len(pairs)} comparisons were made, so the "
              f"threshold is 0.05/{len(pairs)} = {threshold:.3f}\n"
              "(Bonferroni) — not 0.05. Overlapping intervals do not imply "
              "no difference either;\nneither reading is safe by eye.")
        for a, b in pairs:
            p = two_proportion_p(len(a.with_schema), len(a.supa),
                                 len(b.with_schema), len(b.supa))
            if p < threshold:
                verdict = "distinguishable"
            elif p < 0.05:
                verdict = ("below 0.05 but NOT below the corrected threshold "
                           "— expected noise")
            else:
                verdict = "not distinguishable"
            print(f"  {a.stratum.key} vs {b.stratum.key}: p = {p:.3f}"
                  f"  — {verdict}")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps({
        "fetched": "2026-08-18",
        "strata": [{
            "key": r.stratum.key,
            "label": r.stratum.label,
            "candidates": len(r.repos),
            "unreachable": len(r.unreachable),
            "members": len(r.members),
            "uses_supabase": len(r.supa),
            "supabase_is_entry": r.stratum.supabase_is_entry,
            "commits_schema": len(r.with_schema),
            "blind_spot": len(r.blind),
            "blind_spot_ci": wilson(len(r.blind), len(r.supa)),
            "anon_readable": len([x for x in r.with_schema if x.read_findings]),
            "anon_writable": len([x for x in r.with_schema if x.write_findings]),
        } for r in results],
        "repos": [asdict(x) for r in results for x in r.repos],
    }, indent=2))
    print(f"\nwrote {OUT}")

    thin = [r.stratum.key for r in results if len(r.supa) < 25]
    if thin:
        print(f"\nREFUSING TO REPORT A RATE for {', '.join(thin)}: fewer than "
              "25 Supabase repos\nreached. The interval would be as useless as "
              "the 3-of-7 this run exists to replace.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

