// Regenerate the standalone browser's presentation adapter after editing the
// TypeScript source. Requires the locked web development dependencies.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import ts from '../web/node_modules/typescript/lib/typescript.js';

const target = new URL('../browser/src/app.js', import.meta.url);
let current = await readFile(target, 'utf8');
for (const [name, marker, dependency] of [
  ['ownerReport', 'OWNER REPORT', 'securityAgent'],
  ['ownerRoadmap', 'OWNER ROADMAP', 'ownerReport'],
]) {
  const source = new URL(`../web/src/lib/${name}.ts`, import.meta.url);
  const begin = `// BEGIN ${marker} PROJECTION`;
  const end = `// END ${marker} PROJECTION`;
  const compiled = ts.transpileModule(await readFile(source, 'utf8'), {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 },
  }).outputText.replace(new RegExp(`^import .* from "\\./${dependency}";\\n`, 'm'), '')
    .replace(/^export /gm, '').trim();
  if (/^import /m.test(compiled)) throw new Error('The browser projection must use existing local validators only');
  const block = `${begin}\n// Generated by node scripts/sync_owner_report_browser.mjs.\n${compiled}\n${end}`;
  const start = current.indexOf(begin), stop = current.indexOf(end);
  if ((start < 0) !== (stop < 0) || stop >= 0 && stop < start) throw new Error('Invalid projection markers');
  current = start < 0 ? `${current.trimEnd()}\n\n${block}\n`
    : current.slice(0, start) + block + current.slice(stop + end.length);
}
await writeFile(target, current);
console.log(fileURLToPath(target));
